development:
  adapter: postgresql
  database: foody_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: foody_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: foody_production
  pool: 5
  timeout: 5000
